##
# package     InstantSearch on Joomla with Algolia, by Anibal Sanchez @anibal_sanchez - London(#JUGL) Meetup - July
# subpackage  Lando
#
# author      Extly, CB.
# copyright   Copyright (C) 2018 Extly, CB. All rights reserved.
# license     https://www.gnu.org/licenses/gpl-3.0.html GNU/GPL
# link        https://extly.tech
##

name: instant-search-on-joomla-with-algolia

proxy:
  web-service:
    # Give me http://instant-search-on-joomla-with-algolia.lndo.site and https://instant-search-on-joomla-with-algolia.lndo.site
    - instant-search-on-joomla-with-algolia.lndo.site

services:
  web-service:
    # Use the latest version of nginx.
    type: nginx

    # Optionally specify a webroot if it is a subdirectory of the appRoot
    webroot: web
    ports:
      # A nice http://localhost:8080
      - '8080:80'


